import type { Metadata } from 'next'

import { headerConfig } from '@/config'

import { Header } from '@/components/molecules/Header'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-primary text-gray-100">
        <Header items={headerConfig.mainNav} />
        {children}
      </body>
    </html>
  )
}
