import type { Metadata } from 'next'

import { Layout } from '@/components/atoms/Layout'
import { Footer } from '@/components/organisms/Footer'
import { Header } from '@/components/organisms/Header'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-primary text-gray-100">
        <Header />

        <Layout>
          <div className="pt-20">{children}</div>
        </Layout>

        <Footer />
      </body>
    </html>
  )
}
